# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preference_window(object):
    def setupUi(self, preference_window):
        preference_window.setObjectName("preference_window")
        preference_window.resize(871, 970)
        self.centralwidget = QtWidgets.QWidget(preference_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.canvas_tab = QtWidgets.QWidget()
        self.canvas_tab.setObjectName("canvas_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.canvas_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.canvas_tree_view = QtWidgets.QTreeView(self.canvas_tab)
        self.canvas_tree_view.setObjectName("canvas_tree_view")
        self.verticalLayout_2.addWidget(self.canvas_tree_view)
        self.tabWidget.addTab(self.canvas_tab, "")
        self.plot_tab = QtWidgets.QWidget()
        self.plot_tab.setObjectName("plot_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.plot_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.plot_tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.canvas_select = QtWidgets.QComboBox(self.plot_tab)
        self.canvas_select.setObjectName("canvas_select")
        self.horizontalLayout.addWidget(self.canvas_select)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.plot_tree_view = QtWidgets.QTreeView(self.plot_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_tree_view.sizePolicy().hasHeightForWidth())
        self.plot_tree_view.setSizePolicy(sizePolicy)
        self.plot_tree_view.setObjectName("plot_tree_view")
        self.verticalLayout_7.addWidget(self.plot_tree_view)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.add_plot = QtWidgets.QPushButton(self.plot_tab)
        self.add_plot.setObjectName("add_plot")
        self.horizontalLayout_3.addWidget(self.add_plot)
        self.remove_plot = QtWidgets.QPushButton(self.plot_tab)
        self.remove_plot.setObjectName("remove_plot")
        self.horizontalLayout_3.addWidget(self.remove_plot)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.plot_tab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.Properties = QtWidgets.QWidget()
        self.Properties.setObjectName("Properties")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Properties)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.Properties)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 535, 740))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.editor_layout = QtWidgets.QVBoxLayout()
        self.editor_layout.setObjectName("editor_layout")
        self.verticalLayout_5.addLayout(self.editor_layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.tabWidget_2.addTab(self.Properties, "")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Data)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plot_data_view = QtWidgets.QTableView(self.Data)
        self.plot_data_view.setObjectName("plot_data_view")
        self.verticalLayout_4.addWidget(self.plot_data_view)
        self.tabWidget_2.addTab(self.Data, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.plot_tab, "")
        self.io_tab = QtWidgets.QWidget()
        self.io_tab.setObjectName("io_tab")
        self.tabWidget.addTab(self.io_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        preference_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(preference_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 27))
        self.menubar.setObjectName("menubar")
        preference_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(preference_window)
        self.statusbar.setObjectName("statusbar")
        preference_window.setStatusBar(self.statusbar)

        self.retranslateUi(preference_window)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(preference_window)

    def retranslateUi(self, preference_window):
        _translate = QtCore.QCoreApplication.translate
        preference_window.setWindowTitle(_translate("preference_window", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canvas_tab), _translate("preference_window", "Canvas Properties"))
        self.label.setText(_translate("preference_window", "Canvas:"))
        self.add_plot.setText(_translate("preference_window", "+"))
        self.remove_plot.setText(_translate("preference_window", "-"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Properties), _translate("preference_window", "Properties"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Data), _translate("preference_window", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plot_tab), _translate("preference_window", "Plot Properties"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.io_tab), _translate("preference_window", "Load and Save"))

