# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scatter_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScatterWidget(object):
    def setupUi(self, ScatterWidget):
        ScatterWidget.setObjectName("ScatterWidget")
        ScatterWidget.resize(437, 416)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScatterWidget.sizePolicy().hasHeightForWidth())
        ScatterWidget.setSizePolicy(sizePolicy)
        self.formlayout = QtWidgets.QFormLayout(ScatterWidget)
        self.formlayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formlayout.setObjectName("formlayout")
        self.label = QtWidgets.QLabel(ScatterWidget)
        self.label.setObjectName("label")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name = QtWidgets.QLineEdit(ScatterWidget)
        self.name.setObjectName("name")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.line_2 = QtWidgets.QFrame(ScatterWidget)
        self.line_2.setMinimumSize(QtCore.QSize(50, 0))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formlayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.line_check = QtWidgets.QCheckBox(ScatterWidget)
        self.line_check.setObjectName("line_check")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.line_check)
        self.label_3 = QtWidgets.QLabel(ScatterWidget)
        self.label_3.setObjectName("label_3")
        self.formlayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.line_color_button = QtWidgets.QPushButton(ScatterWidget)
        self.line_color_button.setObjectName("line_color_button")
        self.formlayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.line_color_button)
        self.label_4 = QtWidgets.QLabel(ScatterWidget)
        self.label_4.setObjectName("label_4")
        self.formlayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.line_size_input = QtWidgets.QSpinBox(ScatterWidget)
        self.line_size_input.setObjectName("line_size_input")
        self.formlayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line_size_input)
        self.line = QtWidgets.QFrame(ScatterWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formlayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.symbol_check = QtWidgets.QCheckBox(ScatterWidget)
        self.symbol_check.setObjectName("symbol_check")
        self.formlayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.symbol_check)
        self.symbol_combo = QtWidgets.QComboBox(ScatterWidget)
        self.symbol_combo.setObjectName("symbol_combo")
        self.formlayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.symbol_combo)
        self.label_7 = QtWidgets.QLabel(ScatterWidget)
        self.label_7.setObjectName("label_7")
        self.formlayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.symbol_size_input = QtWidgets.QSpinBox(ScatterWidget)
        self.symbol_size_input.setObjectName("symbol_size_input")
        self.formlayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.symbol_size_input)
        self.label_5 = QtWidgets.QLabel(ScatterWidget)
        self.label_5.setObjectName("label_5")
        self.formlayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.symbol_color_button = QtWidgets.QPushButton(ScatterWidget)
        self.symbol_color_button.setObjectName("symbol_color_button")
        self.formlayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.symbol_color_button)
        self.label_6 = QtWidgets.QLabel(ScatterWidget)
        self.label_6.setObjectName("label_6")
        self.formlayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.symbol_color_button_line = QtWidgets.QPushButton(ScatterWidget)
        self.symbol_color_button_line.setObjectName("symbol_color_button_line")
        self.formlayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.symbol_color_button_line)
        self.line_3 = QtWidgets.QFrame(ScatterWidget)
        self.line_3.setMinimumSize(QtCore.QSize(50, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formlayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.label_9 = QtWidgets.QLabel(ScatterWidget)
        self.label_9.setObjectName("label_9")
        self.formlayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.error_color_button = QtWidgets.QPushButton(ScatterWidget)
        self.error_color_button.setObjectName("error_color_button")
        self.formlayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.error_color_button)
        self.label_11 = QtWidgets.QLabel(ScatterWidget)
        self.label_11.setObjectName("label_11")
        self.formlayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.error_size = QtWidgets.QSpinBox(ScatterWidget)
        self.error_size.setObjectName("error_size")
        self.formlayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.error_size)
        self.error_check = QtWidgets.QCheckBox(ScatterWidget)
        self.error_check.setObjectName("error_check")
        self.formlayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.error_check)
        self.label_2 = QtWidgets.QLabel(ScatterWidget)
        self.label_2.setObjectName("label_2")
        self.formlayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.symbol_size_line_input = QtWidgets.QSpinBox(ScatterWidget)
        self.symbol_size_line_input.setObjectName("symbol_size_line_input")
        self.formlayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.symbol_size_line_input)

        self.retranslateUi(ScatterWidget)
        QtCore.QMetaObject.connectSlotsByName(ScatterWidget)

    def retranslateUi(self, ScatterWidget):
        _translate = QtCore.QCoreApplication.translate
        ScatterWidget.setWindowTitle(_translate("ScatterWidget", "Form"))
        self.label.setText(_translate("ScatterWidget", "Name"))
        self.line_check.setText(_translate("ScatterWidget", "Line"))
        self.label_3.setText(_translate("ScatterWidget", "Color"))
        self.line_color_button.setText(_translate("ScatterWidget", "Color"))
        self.label_4.setText(_translate("ScatterWidget", "Thickness"))
        self.symbol_check.setText(_translate("ScatterWidget", "Symbol"))
        self.label_7.setText(_translate("ScatterWidget", "Size"))
        self.label_5.setText(_translate("ScatterWidget", "Color"))
        self.symbol_color_button.setText(_translate("ScatterWidget", "Color"))
        self.label_6.setText(_translate("ScatterWidget", "Line color"))
        self.symbol_color_button_line.setText(_translate("ScatterWidget", "Color"))
        self.label_9.setText(_translate("ScatterWidget", "Color"))
        self.error_color_button.setText(_translate("ScatterWidget", "Color"))
        self.label_11.setText(_translate("ScatterWidget", "Thickness"))
        self.error_check.setText(_translate("ScatterWidget", "Error"))
        self.label_2.setText(_translate("ScatterWidget", "Line size"))

